# a='lokesh'
# print(a.upper())

# print('lokesh'.upper())
# print('LOKESH'.lower())
# print('LOKESH'.casefold())
# print('Lokesh'.isupper())
# print('Lokesh'.islower())
# print('LOKESH'.isupper())
# print('lokesh'.islower())
# print('LoKEsh'.swapcase())
# print('loKEsh coDe'.capitalize())
# print('loKEsh coDe'.title())
# print('Lokesh Py'.istitle())
# print('Lokesh py'.istitle())
# print('Lokesh program'.startswith('N'))
# print('Lokesh program'.startswith('L'))
# print('Lokesh program'.startswith('Lok'))
# print('Lokesh program'.endswith('Lok'))
# print('Lokesh program'.endswith('am'))
# print('Lokesh program'.endswith('gram'))
# print('Lokesh program'.endswith('esh'))
# print(len('lokesh'))
# print('lokesh'.find('k'))
# print('lokesh'.find('h'))
# print('lokesh'.find('l'))
# print('lokesh'.center(100))
# txt="I love mango,mangoes are my favourite fruit"
# print(txt.count('mango'))
# print('lokesh'.isidentifier())
# print('Lokesh'.isidentifier())
# name="hEllo loKEsh"
# print(name.center)
# print(name.center())
# print(name.center(50,'_'))
# print(name.center(100))
# name="heLLo pYthON"
# print(type(name))
# n=name.encode()
# print(n)
# print(n.decode())
# z="heLLo PytHoN"
# print(z.index('1'))
# print(z.index('1',5))
# print(z.index('0'))
# print(z.index('0',4))
# print(z.index('t'))
# print(z.index(1))
# print(z.index('b'))
# print(z.index('n'))
# print(z.index('P'))
# print(z.index('L'))
# print(z.rindex('P'))
# r="hello pyTHOn programming"
# print(len(r))
# print(r.rindex('n'))
# print(r.rindex('m'))
# print(r.rindex('t'))
# print(len('josh innovations'))
# print(len('lokesh'))
# b="_34hello"
# print(b.isidentifier())
# w="how is your day"
# print(w.find('o'))
# print(w.find('r'))
# print(w.find('or'))
# print(len(w))
# print(w.rfind('o'))
# print(w.count('h'))
# print(w.count('i'))
# print(w.count('o'))
# h="python learning"
# print(h.replace('learning', 'programming'))
